### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NOOB-MANTIS** [rydoginator/ACNL-NTR-Cheats#55]
**Issue**
where is this seeder i don't know where it is.

**Version of plugin:**

0.4.0 beta 4 i think

**NTR Version used:**

 NTR v3.6

**Type of 3DS:**

 Old 3DS,

**3DS Firmware Version:**

 11.6.0-39E

**CFW on 3DS:**

 Luma3DS

**ACNL Version:**
 Original ACNL with the v1.5 update

**Source of game:**

Cart,

**Language & Region
 English & Europe

**Extra description of event:**

I heard that you can put down money trees/rocks/pwps/buidings etc in the ocean and island using the seeder but i dont know where the seeder is (the cheat)

**It is also recommended to send us a luma crash dump.
The crash dump will be located at `SD:/luma/dumps/arm11` or `SD:/luma/dumps/arm9`.**

**Comment by LeviSpecialzz** [comment]
The seeder is Real Time World Edit, and as far as I know, you can't use it during a multiplayer session. Visiting someone's town, only you can see it. The other players can't interact with it. On the island, it's completely unusable. If you want a seeder that works in multiplayer, there is a version of this plugin on Reddit, but it's very outdated and breaks frequently. Another way to get a seeder would be to create the cheats yourself using C. I personally don't know how to code in C, but if you do, go ahead. The reason this plugin doesn't have a multiplayer usable seeder is because it can be abused (ex. Placing trees everywhere and making players unable to move). Real Time World Edit can be used as much as you want in single player, but in multiplayer it doesn't function.

**Comment by kokichioumalovesme** [comment]
Question though. If I were to use real time world edit or real time building modifier in single player, then invite someone over, would they see my changes that I made during single player mode? I recently reset my game and I want to use it to replace the PWPs I lost.

**Comment by LeviSpecialzz** [comment]
I am not sure about PWPs, but I know that if you add trees, stumps, etc. using Real Time World Edit in single player, Friends who visit will see the changes. You just can't use it during a town visit.

**Comment by Slattz** [comment]
@kokichioumalovesme I'm sure you figured it out by now, but yea, they'd see the changes if you do it before they come. If you do it while they're there though, they won't see the changes.
